### ISSUE TITLE
find_vert_coord in diagnostics/ensemble/plot_ensemble_zonal.py

### ISSUE THREAD

**Issue by jhardenberg** [DestinE-Climate-DT/AQUA-diagnostics#382]
### machine

Local

### catalog

ci

### version

main

### version

main

### What happened?

Simply doing `pytest tests/timeseries/test_timeseries.py` and using the current AQUA-core main fails with

````
    from .plot_ensemble_zonal import PlotEnsembleZonal
aqua/diagnostics/ensemble/plot_ensemble_zonal.py:5: in <module>
    from aqua.core.util import find_vert_coord
E   ImportError: cannot import name 'find_vert_coord' from 'aqua.core.util' (/Users/jost/git/AQUA/aqua/core/util/__init__.py)
````
`find_vert_coord` has been removed from aqua in favour of `CoordIdentifier`
 It appears only in `diagnostics/ensemble/plot_ensemble_zonal.py` 

This means that AQUA-diagnostics will not work with the upcoming AQUA v1.1.0

### Code to reproduce the issue

```python

```

### Are you interested in making a pull request?

None

**Comment by jhardenberg** [comment]
I have prepared a fix which will work as soon as the new core release comes in #383
